In [1]:
import pandas as pd
import numpy as np

In [ ]:
dict_months = {

    0: 'January',
    1: 'February',
    2: 'March',
    3: 'April',
    4: 'May',
    5: 'June',
    6: 'July',
    7: 'August',
    8: 'September',
    9: 'October',
    10: 'November',
    11: 'December'
    
}

## creates a dictionary that will be referenced later to pull in month names for data frames and monthly data analysis

In [ ]:
df_jan = pd.read_csv('jan_2025_raw_trip_data.csv')
df_feb = pd.read_csv('feb_2025_raw_trip_data.csv')
df_mar = pd.read_csv('mar_2025_raw_trip_data.csv')
df_apr = pd.read_csv('apr_2025_raw_trip_data.csv')
df_may = pd.read_csv('may_2025_raw_trip_data.csv')
df_jun = pd.read_csv('jun_2025_raw_trip_data.csv')
df_jul = pd.read_csv('jul_2025_raw_trip_data.csv')
df_aug = pd.read_csv('aug_2025_raw_trip_data.csv')
df_sep = pd.read_csv('sep_2025_raw_trip_data.csv')
df_oct = pd.read_csv('oct_2025_raw_trip_data.csv')
df_nov = pd.read_csv('nov_2025_raw_trip_data.csv')
df_dec = pd.read_csv('dec_2025_raw_trip_data.csv')

## import all csv files as dataframes

In [ ]:
df_list = [df_jan, df_feb, df_mar, df_apr, df_may, df_jun, df_jul, df_aug, df_sep, df_oct, df_nov, df_dec]

##creates a list of data frames to pefrom opperations on

In [ ]:
list_started_at = []
list_ended_at = []

for i in range(len(df_list)):
    columns_to_check = ['started_at', 'ended_at']
    list_started_at.append(str(df_list[i][columns_to_check[0]].isna().sum()))
    list_ended_at.append(str(df_list[i][columns_to_check[1]].isna().sum()))
print(list_started_at)
print(list_ended_at)

##Checks to make sure there are no na values in the started at or ended at columns of the df

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [ ]:
list_classic_electric = []

for i in range(len(df_list)):
    classic_rideable_values = (df_list[i]['rideable_type'] == 'classic_bike' ).sum()
    electric_rideable_values = (df_list[i]['rideable_type'] == 'electric_bike' ).sum()
    bad_rideable_values = (len(df_list[i]) - classic_rideable_values - electric_rideable_values)
    list_classic_electric.append(str(bad_rideable_values))
print(list_classic_electric)

##Makes sure that the total number of rentals is equal to the mechanical rentals plus the electrical rentals

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [ ]:
list_member_casual = []

for i in range(len(df_list)):
    member_values = (df_list[i]['member_casual'] == 'member' ).sum()
    casual_values = (df_list[i]['member_casual'] == 'casual' ).sum()
    bad_member_values = (len(df_list[i]) - member_values - casual_values)
    list_member_casual.append(str(bad_member_values))
print(list_member_casual)

##makes sure that the total users is equal to the number of casual members plus the number of members

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [ ]:
for i in range(len(df_list)):
    df_list[i]['started_at'] = pd.to_datetime(df_list[i]['started_at'])
    df_list[i]['ended_at'] = pd.to_datetime(df_list[i]['ended_at'])

##converts the started at and ended at columns from a string value to a date time value

In [ ]:
for i in range(len(df_list)):
    df_list[i]['duration'] = df_list[i]['ended_at'] - df_list[i]['started_at']

##adds a column to the df, duration, which measures how long a bike was rented for

In [ ]:
for i in range(len(df_list)):
    df_list[i]['duration_mins'] = (df_list[i]['duration'].dt.total_seconds()/60).round(2)

##converts the date time format into a total minutes float value

In [ ]:
list_illogical_duration = []

for i in range(len(df_list)):
    illoical_duration = (df_list[i]['duration'] < pd.Timedelta(0)).sum()
    list_illogical_duration.append(str(illoical_duration))

print(list_illogical_duration)

## checks to see if any ride durations are illogical, e.g. returned before the ride even started. December has 29 of these values.

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '29']

In [ ]:
df_dec = df_dec[df_dec['duration'] >= pd.Timedelta(0)]

##reduces december to only have rows with a duration > 0

In [ ]:
df_list = [df_jan, df_feb, df_mar, df_apr, df_may, df_jun, df_jul, df_aug, df_sep, df_oct, df_nov, df_dec]
list_illogical_duration_01 = []

for i in range(len(df_list)):
    illoical_duration_01 = (df_list[i]['duration'] < pd.Timedelta(0)).sum()
    list_illogical_duration_01.append(str(illoical_duration_01))

print(list_illogical_duration_01)

## rechecks the above conditions to make sure there are no rows with duration < 0. This is now fixed

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [ ]:
output_list_january = []
output_list_february = []
output_list_march = []
output_list_april = []
output_list_may = []
output_list_june = []
output_list_july = []
output_list_august = []
output_list_september = []
output_list_october = []
output_list_november = []
output_list_december = []

list_output = [
output_list_january,
output_list_february,
output_list_march,
output_list_april,
output_list_may,
output_list_june,
output_list_july,
output_list_august,
output_list_september,
output_list_october,
output_list_november,
output_list_december,

]

for i in range(12):
    list_output[i].append(dict_months[i])
    list_output[i].append(len(df_list[i]))

## creates the lists used to build the output pivot table and starts by appending the months from the dictionary above.

In [ ]:
for i in range(len(list_output)):
    df_mem = df_list[i][df_list[i]['member_casual'] == 'member']
    list_output[i].append(len(df_mem[df_mem['rideable_type'] == 'electric_bike']))
    list_output[i].append(len(df_mem[df_mem['rideable_type'] == 'classic_bike']))
    print(list_output[i])
for i in range(len(list_output)):
    df_casual = df_list[i][df_list[i]['member_casual'] == 'casual']
    list_output[i].append(len(df_casual[df_casual['rideable_type'] == 'electric_bike']))
    list_output[i].append(len(df_casual[df_casual['rideable_type'] == 'classic_bike']))
    print(list_output[i])

##adds rideable type (classic and electric) sums to the lists for members and non members

['January', 178372, 82616, 57380]
['February', 138689, 71553, 42983]
['March', 151880, 78777, 45349]
['April', 298155, 132715, 79571]
['May', 371341, 163157, 98968]
['June', 502456, 201058, 118761]
['July', 678904, 242980, 143831]
['August', 763432, 284399, 155696]
['September', 790177, 289545, 162894]
['October', 714759, 291264, 158034]
['November', 646039, 278726, 143303]
['December', 356599, 169313, 88146]
['January', 178372, 82616, 57380, 25228, 13148]
['February', 138689, 71553, 42983, 17518, 6635]
['March', 151880, 78777, 45349, 20347, 7407]
['April', 298155, 132715, 79571, 54427, 31442]
['May', 371341, 163157, 98968, 69552, 39664]
['June', 502456, 201058, 118761, 115302, 67335]
['July', 678904, 242980, 143831, 181809, 110284]
['August', 763432, 284399, 155696, 213782, 109555]
['September', 790177, 289545, 162894, 219651, 118087]
['October', 714759, 291264, 158034, 184166, 81295]
['November', 646039, 278726, 143303, 157385, 66625]
['December', 356599, 169313, 88146, 71836, 27304]

In [ ]:
for i in range(len(list_output)):
    list_output[i].append(len(df_list[i][df_list[i]['member_casual'] == 'member']))
    list_output[i].append(len(df_list[i][df_list[i]['member_casual'] == 'casual']))
    print(list_output[i])

## appends the total number of casual and members for cyclistic

['January', 178372, 82616, 57380, 25228, 13148, 139996, 38376]
['February', 138689, 71553, 42983, 17518, 6635, 114536, 24153]
['March', 151880, 78777, 45349, 20347, 7407, 124126, 27754]
['April', 298155, 132715, 79571, 54427, 31442, 212286, 85869]
['May', 371341, 163157, 98968, 69552, 39664, 262125, 109216]
['June', 502456, 201058, 118761, 115302, 67335, 319819, 182637]
['July', 678904, 242980, 143831, 181809, 110284, 386811, 292093]
['August', 763432, 284399, 155696, 213782, 109555, 440095, 323337]
['September', 790177, 289545, 162894, 219651, 118087, 452439, 337738]
['October', 714759, 291264, 158034, 184166, 81295, 449298, 265461]
['November', 646039, 278726, 143303, 157385, 66625, 422029, 224010]
['December', 356599, 169313, 88146, 71836, 27304, 257459, 99140]

In [ ]:
for i in range(len(list_output)):
    df_members = df_list[i][df_list[i]['member_casual'] == 'member']
    df_casual = df_list[i][df_list[i]['member_casual'] == 'casual']

    list_output[i].append(str(df_members['duration_mins'].mean()))
    list_output[i].append(str(df_casual['duration_mins'].mean()))
    print(list_output[i])

##adds the total number of float minutes of rental for members and casual rentals

['January', 178372, 82616, 57380, 25228, 13148, 139996, 38376, '10.76379232263779', '17.755763498019594']
['February', 138689, 71553, 42983, 17518, 6635, 114536, 24153, '10.073934920025145', '14.710406988779862']
['March', 151880, 78777, 45349, 20347, 7407, 124126, 27754, '9.993693102170374', '14.397951646609497']
['April', 298155, 132715, 79571, 54427, 31442, 212286, 85869, '11.267538273838124', '20.85386821786675']
['May', 371341, 163157, 98968, 69552, 39664, 262125, 109216, '11.326354563662374', '21.507462642836217']
['June', 502456, 201058, 118761, 115302, 67335, 319819, 182637, '12.115591068698231', '23.837889912777808']
['July', 678904, 242980, 143831, 181809, 110284, 386811, 292093, '12.952918350305449', '25.558535843036292']
['August', 763432, 284399, 155696, 213782, 109555, 440095, 323337, '13.351122825753531', '24.340118235772582']
['September', 790177, 289545, 162894, 219651, 118087, 452439, 337738, '13.099092010193639', '23.52954971013034']
['October', 714759, 291264, 158034, 184166, 81295, 449298, 265461, '12.674150252171163', '21.779956377773008']
['November', 646039, 278726, 143303, 157385, 66625, 422029, 224010, '12.369323695764981', '20.459260434802015']
['December', 356599, 169313, 88146, 71836, 27304, 257459, 99140, '12.152375718075499', '18.23898053258019']

In [18]:
print(type(output_list_april[7]))

<class 'int'>

In [ ]:
output_columns = ['month', 'total_rides', 'mem_elec_bike', 'mem_classic_bike', 'casual_elec_bike', 'casual_classic_bike', 'member', 'casual', 'avg_mem_duration_mins', 
                  'avg_casual_duration_mins']
df_output_monthly = pd.DataFrame(columns=output_columns)

for i in range(len(list_output)):
    df_output_monthly.loc[len(df_output_monthly)] = list_output[i]
df_output_monthly.head(12)

## creates a wide df from the previous info

,month,total_rides,mem_elec_bike,mem_classic_bike,casual_elec_bike,casual_classic_bike,member,casual,avg_mem_duration_mins,avg_casual_duration_mins
0,January,178372,82616,57380,25228,13148,139996,38376,10.76379232263779,17.755763498019594
1,February,138689,71553,42983,17518,6635,114536,24153,10.073934920025145,14.710406988779862
2,March,151880,78777,45349,20347,7407,124126,27754,9.993693102170374,14.397951646609497
3,April,298155,132715,79571,54427,31442,212286,85869,11.267538273838124,20.85386821786675
4,May,371341,163157,98968,69552,39664,262125,109216,11.326354563662374,21.507462642836217
5,June,502456,201058,118761,115302,67335,319819,182637,12.115591068698231,23.837889912777808
6,July,678904,242980,143831,181809,110284,386811,292093,12.952918350305449,25.558535843036292
7,August,763432,284399,155696,213782,109555,440095,323337,13.351122825753531,24.340118235772582
8,September,790177,289545,162894,219651,118087,452439,337738,13.099092010193639,23.52954971013034
9,October,714759,291264,158034,184166,81295,449298,265461,12.674150252171163,21.779956377773008
10,November,646039,278726,143303,157385,66625,422029,224010,12.369323695764981,20.459260434802015
11,December,356599,169313,88146,71836,27304,257459,99140,12.152375718075499,18.23898053258019

In [177]:
df_output_monthly.to_csv('cleaned_monthly_data.csv', index=False)

In [ ]:
output_list_january_mem = []
output_list_january_cas = []
output_list_february_mem = []
output_list_february_cas = []
output_list_march_mem = []
output_list_march_cas = []
output_list_april_mem = []
output_list_april_cas = []
output_list_may_mem = []
output_list_may_cas = []
output_list_june_mem = []
output_list_june_cas = []
output_list_july_mem = []
output_list_july_cas = []
output_list_august_mem = []
output_list_august_cas = []
output_list_september_mem = []
output_list_september_cas = []
output_list_october_mem = []
output_list_october_cas = []
output_list_november_mem = []
output_list_november_cas = []
output_list_december_mem = []
output_list_december_cas = []

list_output_cas = [
output_list_january_cas,
output_list_february_cas,
output_list_march_cas,
output_list_april_cas,
output_list_may_cas,
output_list_june_cas,
output_list_july_cas,
output_list_august_cas,
output_list_september_cas,
output_list_october_cas,
output_list_november_cas,
output_list_december_cas,

]

list_output_mem = [

output_list_january_mem,
output_list_february_mem,
output_list_march_mem,
output_list_april_mem,
output_list_may_mem,
output_list_june_mem,
output_list_july_mem,
output_list_august_mem,
output_list_september_mem,
output_list_october_mem,
output_list_november_mem,
output_list_december_mem,

]

for i in range(12):
    list_output_mem[i].append(dict_months[i])
    list_output_cas[i].append(dict_months[i])
    list_output_mem[i].append('member')
    list_output_cas[i].append('casual')
    print(list_output_mem[i])
    print(list_output_cas[i])

##this section of the code turns the wide pivot table above into a tall pivot table to support some different data visuals
##starts by appending each month for both member and non member

['January', 'member']
['January', 'casual']
['February', 'member']
['February', 'casual']
['March', 'member']
['March', 'casual']
['April', 'member']
['April', 'casual']
['May', 'member']
['May', 'casual']
['June', 'member']
['June', 'casual']
['July', 'member']
['July', 'casual']
['August', 'member']
['August', 'casual']
['September', 'member']
['September', 'casual']
['October', 'member']
['October', 'casual']
['November', 'member']
['November', 'casual']
['December', 'member']
['December', 'casual']

In [ ]:
df_list = [df_jan, df_feb, df_mar, df_apr, df_may, df_jun, df_jul, df_aug, df_sep, df_oct, df_nov, df_dec]
for i in range(12):
    list_output_mem[i].append(len(df_list[i][df_list[i]['member_casual'] == 'member']))
    list_output_cas[i].append(len(df_list[i][df_list[i]['member_casual'] == 'casual']))
    print(list_output_mem[i])
    print(list_output_cas[i])

##calculates the total member and casual renters per month

['January', 'member', 139996]
['January', 'casual', 38376]
['February', 'member', 114536]
['February', 'casual', 24153]
['March', 'member', 124126]
['March', 'casual', 27754]
['April', 'member', 212286]
['April', 'casual', 85869]
['May', 'member', 262125]
['May', 'casual', 109216]
['June', 'member', 319819]
['June', 'casual', 182637]
['July', 'member', 386811]
['July', 'casual', 292093]
['August', 'member', 440095]
['August', 'casual', 323337]
['September', 'member', 452439]
['September', 'casual', 337738]
['October', 'member', 449298]
['October', 'casual', 265461]
['November', 'member', 422029]
['November', 'casual', 224010]
['December', 'member', 257459]
['December', 'casual', 99140]

In [ ]:
for i in range(len(list_output)):
    df_mem = df_list[i][df_list[i]['member_casual'] == 'member']
    list_output_mem[i].append(len(df_mem[df_mem['rideable_type'] == 'electric_bike']))
    list_output_mem[i].append(len(df_mem[df_mem['rideable_type'] == 'classic_bike']))
    print(list_output_mem[i])
    df_cas = df_list[i][df_list[i]['member_casual'] == 'casual']
    list_output_cas[i].append(len(df_cas[df_cas['rideable_type'] == 'electric_bike']))
    list_output_cas[i].append(len(df_cas[df_cas['rideable_type'] == 'classic_bike']))
    print(list_output_cas[i])

##calculates classic vs electric bike for members vs nonmembers

['January', 'member', 139996, 82616, 57380]
['January', 'casual', 38376, 25228, 13148]
['February', 'member', 114536, 71553, 42983]
['February', 'casual', 24153, 17518, 6635]
['March', 'member', 124126, 78777, 45349]
['March', 'casual', 27754, 20347, 7407]
['April', 'member', 212286, 132715, 79571]
['April', 'casual', 85869, 54427, 31442]
['May', 'member', 262125, 163157, 98968]
['May', 'casual', 109216, 69552, 39664]
['June', 'member', 319819, 201058, 118761]
['June', 'casual', 182637, 115302, 67335]
['July', 'member', 386811, 242980, 143831]
['July', 'casual', 292093, 181809, 110284]
['August', 'member', 440095, 284399, 155696]
['August', 'casual', 323337, 213782, 109555]
['September', 'member', 452439, 289545, 162894]
['September', 'casual', 337738, 219651, 118087]
['October', 'member', 449298, 291264, 158034]
['October', 'casual', 265461, 184166, 81295]
['November', 'member', 422029, 278726, 143303]
['November', 'casual', 224010, 157385, 66625]
['December', 'member', 257459, 169313, 88146]
['December', 'casual', 99140, 71836, 27304]

In [ ]:
output_columns = ['month', 'member_casual', 'mem_cas_count', 'elec_bike', 'classic_bike']
df_output_monthly_short = pd.DataFrame(columns=output_columns)

for i in range(len(list_output)):
    df_output_monthly_short.loc[len(df_output_monthly_short)] = list_output_mem[i]
    df_output_monthly_short.loc[len(df_output_monthly_short)] = list_output_cas[i]
df_output_monthly_short.head(24)

##builds and prints the tall df

        month member_casual  mem_cas_count  elec_bike  classic_bike
0     January        member         139996      82616         57380
1     January        casual          38376      25228         13148
2    February        member         114536      71553         42983
3    February        casual          24153      17518          6635
4       March        member         124126      78777         45349
5       March        casual          27754      20347          7407
6       April        member         212286     132715         79571
7       April        casual          85869      54427         31442
8         May        member         262125     163157         98968
9         May        casual         109216      69552         39664
10       June        member         319819     201058        118761
11       June        casual         182637     115302         67335
12       July        member         386811     242980        143831
13       July        casual         292093     181809        110284
14     August        member         440095     284399        155696
15     August        casual         323337     213782        109555
16  September        member         452439     289545        162894
17  September        casual         337738     219651        118087
18    October        member         449298     291264        158034
19    October        casual         265461     184166         81295
20   November        member         422029     278726        143303
21   November        casual         224010     157385         66625
22   December        member         257459     169313         88146
23   December        casual          99140      71836         27304

In [45]:
df_output_monthly_short.to_csv('cleaned_monthly_short_data.csv', index=False)